# CM hardware
#BOARD_HARDWARE_CLASS := $(LOCAL_PATH)/cmhw

# MTK Hardware
BOARD_HAS_MTK_HARDWARE := true
BOARD_USES_MTK_HARDWARE := true
MTK_HARDWARE := true
BOARD_GLOBAL_CFLAGS += -DADD_LEGACY_ACQUIRE_BUFFER_SYMBOL

# Ashmem
DISABLE_ASHMEM_TRACKING := true
